
import { Habit, HabitCategory } from './types';

export const INITIAL_HABITS: Habit[] = [
  {
    id: '1',
    name: 'Treino Matinal',
    description: '30 min de cardio',
    category: HabitCategory.FITNESS,
    goal: '30 min',
    completedDays: [],
    color: 'orange',
    frequency: 'diário',
  },
  {
    id: '2',
    name: 'Ler 10 páginas',
    description: 'Hábitos Atômicos',
    category: HabitCategory.READING,
    goal: '10 pág',
    completedDays: [],
    color: 'blue',
    frequency: 'diário',
  },
  {
    id: '3',
    name: 'Beber Água',
    description: 'Meta: 3000ml',
    category: HabitCategory.WATER,
    goal: '3000ml',
    targetValue: 3000,
    currentValue: 2000,
    completedDays: [],
    color: 'indigo',
    frequency: 'diário',
  },
  {
    id: '4',
    name: 'Meditar',
    description: '15 min de mindfulness',
    category: HabitCategory.MEDITATION,
    goal: '15 min',
    completedDays: [],
    color: 'purple',
    frequency: 'diário',
  },
  {
    id: '5',
    name: 'Dormir Cedo',
    description: 'Antes das 23:00',
    category: HabitCategory.SLEEP,
    goal: '23:00',
    completedDays: [],
    color: 'yellow',
    frequency: 'diário',
  },
];
